# Generated by Django 5.2 on 2025-05-01 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cti', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefendMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='DetectionMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='DefendCoverageEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coverage', models.FloatField(default=1.0)),
                ('technique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defend_entries', to='cti.technique')),
                ('telemetry_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defend_entries', to='cti.telemetrysource')),
                ('matrix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coverage_entries', to='defend.defendmatrix')),
            ],
        ),
        migrations.CreateModel(
            name='DetectionCoverageEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coverage', models.FloatField()),
                ('technique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detection_entries', to='cti.technique')),
                ('telemetry_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detection_entries', to='cti.telemetrysource')),
                ('matrix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='defend.detectionmatrix')),
            ],
        ),
    ]
