# Generated by Django 5.2 on 2025-05-01 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Technique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mitre_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='TelemetrySource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='APTGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('regions', models.ManyToManyField(related_name='apt_groups', to='cti.region')),
                ('sectors', models.ManyToManyField(related_name='apt_groups', to='cti.sector')),
            ],
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('frequency', models.FloatField(default=0.0, help_text='Normalized usage frequency (0.0 - 1.0)')),
                ('rarity', models.FloatField(default=0.0, help_text='Relative rarity (0.0 - 1.0)')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedures', to='cti.aptgroup')),
                ('technique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedures', to='cti.technique')),
                ('telemetry_sources', models.ManyToManyField(related_name='procedures', to='cti.telemetrysource')),
            ],
        ),
    ]
